default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rjpa_development
test:
  <<: *default
  database: rjpa_test
production:
  <<: *default
  database: rjpa_production
  username: postgres
  password: <%= ENV['RUBY_JWT_POSTGRES_AUTH_DATABASE_PASSWORD'] %>
